cloud:
  aws:
    credentials:
      access-key: AKIARTZAAXBZOSAG3J4D
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: sunku

server:
  port: 8080


